devph:
  app:
    jwtExpirationMs: '86400000'
    jwtSecret: ======================BezKoder=Spring===========================
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/DevPH
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update
